DROP TABLE POLIZAS;
DROP TABLE TIPOS_POLIZAS;
DROP TABLE MOVIMIENTOS_CUENTAS;
DROP TABLE TIPO_MOVIMIENTOS;
DROP TABLE CUENTASCLIENTES;
DROP TABLE CUENTAS;
DROP TABLE TIPO_CUENTAS;
DROP TABLE CLIENTES;
DROP TABLE CLIENTES;
DROP TABLE TIPO_PERMISOS;

PURGE recyclebin;
COMMIT;
